services:
  - type: web
    name: innoweb-uz
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXTAUTH_URL
        value: https://innoweb-uz.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
